# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run:
    desc: Run app
    deps:
    cmds:
      - task up
      - task migrate
      - go run cmd/sso/main.go --config=./config/local.yaml

  up:
    desc: Start PostgresSQL
    cmds:
      - docker compose up -d postgres

  down:
    desc: Stop docker container
    cmds:
      - docker compose down --remove-orphans

  clean:
    desc: Stop containers and remove volumes
    cmds:
      - docker compose down -v --remove-orphans

  migrate:
    desc: Run migrations
    cmds:
      - docker compose run --rm migrator

  test:
    desc: Run all tests
    deps:
    cmds:
      - task up
      - task migrate
      - go test -v ./...